[package]
name = "http-stream"
version = "0.11.0"
authors = ["nikos <nikos@mugsoft.io>"]
edition = "2018"
license = "MIT"
repository="https://github.com/nikosEfthias/http-streamer"
description="Http json streaming library"

[dependencies]
serde= "1.0"
serde_json="1.0"
